### ISSUE TITLE
Docker image runs version 4.0.6

### ISSUE THREAD

**Issue by diegojserrano** [openmeetings/openmeetings-docker#10]
I am trying to run OM 5.0.0 and started by running the prebuilt docker image with the following command: 

docker run -i --rm --name om-server -p 5443:5443 -p 8888:8888 openmeetings-docker-images.bintray.io/server:latest

But docker downloaded version 4.0.6. Is the image name right? On the 4.0.6 version readme.md the image name is the same.

Should I build it with docker?

**Comment by solomax** [comment]
Latest docker image uses latest release ... So I see no issues here :)
To run 5.0.0 you should build it locally
Please let me know if there will be any issues :)

**Comment by diegojserrano** [comment]
Thanks! I'll try to build it.
