### ISSUE TITLE
Windows Setup

### ISSUE THREAD

**Issue by user18x** [openmeetings/openmeetings-docker#12]
Hi,

can you please make a setup for windows installations (after "uprade" adobe flash player with html5) with **all** required files/software?
It should be possible at installation to check/uncheck what to install.
I don't need pdf's so i don't need ghostscript.

**Comment by solomax** [comment]
It's not clear what do you mean by "windows installations"
It is docker, you can run it under any OS

**Comment by user18x** [comment]
I don't know where to post this, so i post it here.
It has nothing to do with docker!

**Comment by solomax** [comment]
Please write your question to user@ mailing list: https://openmeetings.apache.org/mailing-lists.html (you have to subscribe first)

ps you can try to use search https://openmeetings.markmail.org before asking ...
