### ISSUE TITLE
Please add packages for ldap support to the image

### ISSUE THREAD

**Issue by nevotheless** [openmeetings/openmeetings-docker#15]
Howdy, 

first of all, you've ne Idea how thankful i am that this finally exists (officially)... We would like to help, test and stuff regardless of the state of this docker image for openmeetings but to do so we kinda need ldap support to immediately raise acceptance with our Grey-bearded supervisors.

A co-worker of mine fiddled around with ldap but came to the conclusion that actual ldap packages are required on the `system` / `container` to be able to do ldap. (I hope he's right and didn't tell me something half true, and i couldn't verify it properly yet, since i'm not a super expert with openmeetings.)

But if it's true, would it be possible to include the needed packages within the next image builds? That would be quite awesome.
👋

**Comment by solomax** [comment]
LDAP support is bundled since forever :)
All you need is 

1. map external `omdata` as described here https://github.com/openmeetings/openmeetings-docker#to-run-mini-om-locally-built
2. put config for your LDAP to `omdata/conf`
3. add entry to `OM UI -> Admin -> LDAP`

**Comment by nevotheless** [comment]
Okay will do, thanks!
