### ISSUE TITLE
Can't view others in full server

### ISSUE THREAD

**Issue by Wenlong0913** [openmeetings/openmeetings-docker#16]
The server is started by using this command
```
docker run -i --rm --name om-server-full --expose=5443 --expose=8888 -p 5443:5443 -p 8888:8888 apache/openmeetings:5.0.0-M3
```
It starts successfully, after my friend and I enter the room, both of us can only view our own camera live stream, but we can't see each other.

Here is the error logs:
```
org.kurento.client.internal.server.KurentoServerException: Error adding candidate (Code:40401, Type:null, Data: {"type":"ICE_ADD_CANDIDATE_ERROR"})
```

Any help will be greatly appreciated.

**Comment by solomax** [comment]
Most probably you need to set up TURN server
