### ISSUE TITLE
I have error in /var/log/kurento-media-server/errors.log，help me  please!

### ISSUE THREAD

**Issue by xdzhwxdzhw** [openmeetings/openmeetings-docker#18]
I have error in /var/log/kurento-media-server/errors.log，help me  please!

2020-03-06T23:39:09+00:00 -- New execution
0:00:00.189860491   548 0x55adc3ceca10 WARN                  ladspa gstladspa.c:455:plugin_init: no LADSPA plugins found, check LADSPA_PATH
0:00:00.352974953   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0x120000:'AVR (Audio Visual Research)' is not mapped
0:00:00.353028617   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0x180000:'CAF (Apple Core Audio File)' is not mapped
0:00:00.353035583   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0x100000:'HTK (HMM Tool Kit)' is not mapped
0:00:00.353042560   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0xc0000: 'MAT4 (GNU Octave 2.0 / Matlab 4.2)' is not mapped
0:00:00.353048246   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0xd0000: 'MAT5 (GNU Octave 2.1 / Matlab 5.0)' is not mapped
0:00:00.353053657   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0x210000:'MPC (Akai MPC 2k)' is not mapped
0:00:00.353059926   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0xe0000: 'PVF (Portable Voice Format)' is not mapped
0:00:00.353070182   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0x160000:'SD2 (Sound Designer II)' is not mapped
0:00:00.353078764   548 0x55adc3ceca10 WARN                 default gstsf.c:98:gst_sf_create_audio_template_caps: format 0x190000:'WVE (Psion Series 3)' is not mapped
0:00:00.623402568   537 0x55e802d54cd0 WARN            GST_REGISTRY gstregistry.c:1830:gst_update_registry: registry update failed: Error writing registry cache to /nonexistent/.cache/gstreamer-1.5/registry.x86_64.bin: No such file or directory

**Comment by solomax** [comment]
Hello @xdzhwxdzhw, 
Do you have any issues with Audio/Video?

Above warnings looks like server doesn't have some client codecs
Shouldn't be an issue ....

**Comment by xdzhwxdzhw** [comment]
> Hello @xdzhwxdzhw,
> Do you have any issues with Audio/Video?
> 
> Above warnings looks like server doesn't have some client codecs
> Shouldn't be an issue ....

I solved all the problems，Audio/Video need to configure turn server!

**Comment by knedlyk** [comment]
How did you do that? Can you post your solution, how did you set up turn server for kurento? Via environmental variables? How?

**Comment by xdzhwxdzhw** [comment]
1. mkdir /nonexistent
    chmod 777 /nonexistent
2. install turn server
docker pull instrumentisto/coturn
vi /home/turnserver/turnserver.conf
listening-port=3478
listening-ip=xxx.xxx.xxx.xxx
relay-ip=xxx.xxx.xxx.xxx
external-ip=xxx.xxx.xxx.xxx
relay-threads=50
min-port=41369
max-port=65535
user=kurento:kurento
lt-cred-mech

docker run -d --network=host -v /home/turnserver/turnserver.conf:/etc/coturn/turnserver.conf --name turnserver instrumentisto/coturn  -r=xxx.xxx.xxx.xxx:3478

test turnserver
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
input:
turn:xxx.xxx.xxx.xxx
kurento
kurento

operate in meetingserver docker

vi /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
turnURL=kurento:kurento@xxx.xxx.xxx.xxx:3478

reboot docker

**Comment by knedlyk** [comment]
Thanks, but why do you need turn server, does your kurento server is behind nat?

**Comment by solomax** [comment]
Hello,

You can pass external turn server params using `TURN_URL`, `TURN_USER`, `TURN_PASS`
I'll add these params to README :)

**Comment by solomax** [comment]
Can this issue be closed?

**Comment by xdzhwxdzhw** [comment]
ok,close
