### ISSUE TITLE
Problem with Sound, Mic and cam

### ISSUE THREAD

**Issue by msh-shf** [openmeetings/openmeetings-docker#19]
Hello, I've used this docker container every thing is Ok but about hearing sound of people and see their cam there are problems. 
No body can hear sound and cam of other people, everyone just can see his own camera.
Thankyou

**Comment by solomax** [comment]
Hello @mhd-shf,
TURN server is required for users from different network segments
Have you set up one and have specified it via https://github.com/openmeetings/openmeetings-docker/blob/master/Dockerfile#L38 ENV vars?

**Comment by yegorovae** [comment]
what parameters are needed? don't understand
thanks

**Comment by solomax** [comment]
These: https://github.com/openmeetings/openmeetings-docker#useful-parameters :)))
