### ISSUE TITLE
sql failed to start

### ISSUE THREAD

**Issue by activedecay** [openmeetings/openmeetings-docker#2]
I have an ubuntu VM created with vagrant, installed docker with debops.docker ansible role, cloned this repo, and typed `docker build .` 

it failed to start mysql.

does the master branch work? should I try another git-tagged version, check that out and build again?

I'll update with the error message. Just wondering how well supported this project is

**Comment by solomax** [comment]
Should work as expected
I'll double check

**Comment by solomax** [comment]
Please provide your steps :)

**Comment by activedecay** [comment]
good deal!

i have a vagrant box using a ceph/ubuntu-xenial basebox

    # vagrant init ceph/ubuntu-xenial
    # vagrant up
    # vagrant ssh

the prompt is now vagrant@thebox:~$ 

   1.  sudo apt-get remove docker docker-engine docker.io
   1.  sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
   1.  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
   1.  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs)  stable"
   1.  sudo apt-get update
   1.  sudo apt-get install -y docker-ce
   1.  sudo usermod -aG docker $USER
   1.  sudo systemctl enable docker
   1.  logout and log back in to enable the group changes to the user

do the needful

    git clone https://github.com/openmeetings/openmeetings-docker.git
    cd openmeetings-docker
    nohup docker build . &

a link to nohup.out https://drive.google.com/file/d/0B-Yoemv8xz62RF9GNTVOOHRWeWs/view?usp=sharing

**Comment by activedecay** [comment]
please check the link for output

**Comment by solomax** [comment]
Will try to check the script(s) tonight, seems MySql server was updated and have to be installed differently
Maybe will switch to PostgeSql

**Comment by solomax** [comment]
Should work now, please check

**Comment by activedecay** [comment]
i dunno, but seems like the same failure
https://drive.google.com/file/d/0BwKUTsk23OzZRnpwNHpJN2o4U3M/view?usp=sharing

**Comment by solomax** [comment]
hmm, you have 
```
 * Starting MySQL database server mysqld
   ...fail!
```
in your logs ....
not sure why, will try to reproduce

**Comment by solomax** [comment]
Can you start thr Docker and try to start MySql manually? What would be the error?

**Comment by activedecay** [comment]
after messing around, I finally figured out what `__HASH__` means. it's the IMAGE ID found when executing `docker image ls` -- and it's the one without a repository, i guess...

This shows up in the mysql error log
```
2017-10-16T15:34:33.731594Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table storage engine for 'proxies_priv' doesn't have this option
2017-10-16T15:34:33.731679Z 0 [ERROR] Aborting
```

full context: https://hastebin.com/dewitiyuwu.pl

**Comment by activedecay** [comment]
https://serverfault.com/a/872576/398062 is this the solution? the stackoverflow question is nearly identical to my experience.

**Comment by solomax** [comment]
Sorry, don't have much time to test right now :(((
You can login to docker image as described in README:
```
docker run -it __HASH__
```

**Comment by activedecay** [comment]
i've been editing my comments, please see above. the sql error and the stackoverflow solution don't seem to work. thanks for your time, no rush

**Comment by solomax** [comment]
Hello, just performed clean install using:

```
docker rmi -f $(docker images -a -q)
docker build .
docker run -it __HASH__
```

all good :((
Docker: latest under Ubuntu 17.04
Maybe you are performing any additional steps?

**Comment by activedecay** [comment]
I'll try under 17.04 I've been using 16.04 🌶️

**Comment by solomax** [comment]
should be the same, will try using 16.04 later this week
Docker image is based on 16.04 ....
something weird :(

**Comment by solomax** [comment]
Checking on 16.04 ...
Oracle java8 fails to be downloaded, will double-check tomorrow and will replace with openjdk ...

**Comment by activedecay** [comment]
Nice catch!

**Comment by solomax** [comment]
Will also try to build and publish image, so it will be available without re-building

**Comment by solomax** [comment]
Please try with pre-built latest image: `docker run -i --rm --name om-server -p 5080:5080 -p 1935:1935 openmeetings-docker-registry.bintray.io/server:latest`
Works for me as expected

**Comment by activedecay** [comment]
docker: Error response from daemon: unauthorized: Repository '/openmeetings/registry' does not support Docker API version v2.

```
~$ docker run -i --rm --name om-server -p 5080:5080 -p 1935:1935 openmeetings-docker-registry.bintray.io/server:latest
Unable to find image 'openmeetings-docker-registry.bintray.io/server:latest' locally
docker: Error response from daemon: unauthorized: Repository '/openmeetings/registry' does not support Docker API version v2.
See 'docker run --help'.
```

**Comment by activedecay** [comment]
Docker version 17.09.0-ce, build afdb6d4

**Comment by solomax** [comment]
I have tested on Ubuntu 16.04
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
```
Will try to check on Ubuntu 17.10 and find workaround ...

**Comment by solomax** [comment]
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
```
Also works on my machine, will double-check tonight on different machine

**Comment by solomax** [comment]
Seems to be reproducible :((((
Will try to find what is wrong :(

**Comment by JohnnyC1951** [comment]
I am getting exactly the same today on Ubuntu 16.04 using a plain vanilla docker build with today's image.  Also seeing this during build:
at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
... 33 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Just for info

**Comment by andreasferber** [comment]
I experienced the same problem. I solved it by switching to MariaDB instead, by doing the following

- Replace `apt-get install mysql-server mysql-client` with `apt-get install mariadb-server mariadb-client`
- Remove `-u root -p${DB_ROOT_PASS}` from the mysql calls in scripts/om_install.sh, they aren't necessary with MariaDB for unix socket connections

**Comment by solomax** [comment]
Hopefully I was able to fix this
Could you try new image:
```
docker run -i --rm --name om-server -p 5080:5080 -p 1935:1935 openmeetings-docker-images.bintray.io/server:latest
```

**Comment by JohnnyC1951** [comment]
Just a quick question? Is there any persistence built into this image?

**Comment by solomax** [comment]
What do you mean by persistence?

**Comment by JohnnyC1951** [comment]
Simple example, if you installed some new features in the Docker Image, and you unloaded and reloaded the docker, would the changes survive? They won't unless you have some special strategy.

**Comment by solomax** [comment]
This is my first docker image :)
It is created to simplify "run and test" process :)

PRs are welcome :) The only "special strategy" I can imagine is to use external DB :) ....

**Comment by JohnnyC1951** [comment]
There are 'Data Volumes' and other strategies. [http://www.computerweekly.com/feature/Docker-storage-how-to-get-persistent-storage-in-Docker](url)

**Comment by solomax** [comment]
Thanks! Will try to check these docs and add persistence

**Comment by activedecay** [comment]
your instructions work now. thanks you can probably close this

**Comment by solomax** [comment]
Thanks for checking!
