### ISSUE TITLE
Cant push docker image

### ISSUE THREAD

**Issue by redoxate** [openmeetings/openmeetings-docker#20]
Hello,
I'm trying to push the docker img, I logged in via my docker account :
`docker login --username medreda `
then
`docker tag apache/openmeetings:5.0.0-M3 medreda/apache/openmeetings:5.0.0-M3`

`docker push medreda/apache/openmeetings:5.0.0-M3    `

_denied: requested access to the resource is denied_

Thanks for your time

**Comment by solomax** [comment]
The answer is obvious: You don't have right to push to Apache repo
Why are you trying to do it?

M3 is already pushed, and it is responsibility of Apache OpenMeetings devs ....

**Comment by redoxate** [comment]
Hello , sorry for the spam, I don't know if you saw my other message, 

In order to run the docker image for the first time, just following the readMe,I did successfully : 

`docker build -t apache/openmeetings:5.0.0-M3 --build-arg BUILD_TYPE=full .   `    

before docker run I have to :` docker push apache/openmeetings:5.0.0-M3`

Right ?

**Comment by solomax** [comment]
Already answered in JIRA
