### ISSUE TITLE
Run openeemeetings without TSL

### ISSUE THREAD

**Issue by noddy09** [openmeetings/openmeetings-docker#21]
I'm running multiple web-applications and all are managed by nginx.
Since my other webapps don't have TLS on, and I have not configured SSL for my host (I don't want to it for time being).  So my nginx server is not listening on 443 right now, then How can i proxy pass to openmeetnig port without TSL?

**Comment by solomax** [comment]
OM works on ports 
1. 5080 - insecure
2. 5443 - secure

you can use insecure version but Camera/Microphone will be inaccessible
