### ISSUE TITLE
Can not get video and audio working

### ISSUE THREAD

**Issue by lfarndt** [openmeetings/openmeetings-docker#22]
Hi,
i am just testing openmeeting for our purposes.

I started a docker container with 
docker run -i --rm --expose=5443 --expose=8888 -p 5443:5443 -p 8888:8888 apache/openmeetings:5.0.0-M3

Now i can connect to the server and enter a meeting room.
When i enter the room from a second computer i see that the partner entered the room, but no audio an video is provided.

I see myself but not more

Can you help me?

Thx
Wolfgang

**Comment by solomax** [comment]
Please use `apache/openmeetings:5.0.0-M3.1` image and set up TURN server as described
here https://github.com/openmeetings/openmeetings-docker#useful-parameters
