### ISSUE TITLE
/bin/sh: 1: Syntax error: "&&" unexpected

### ISSUE THREAD

**Issue by collisiondetection** [openmeetings/openmeetings-docker#23]
Get syntax error when running :

docker build -t apache/openmeetings:min-5.0.0-M4 .

or 

docker build -t apache/openmeetings:5.0.0-M4 --build-arg BUILD_TYPE=full https://raw.githubusercontent.com/openmeetings/openmeetings-docker/master/Dockerfile

Step 33/38 : RUN cat /etc/issue     && echo "OM server of type ${OM_TYPE} will be built"     && apt-get update && apt-get install -y --no-install-recommends     apt-utils   && apt-get install -y --no-install-recommends     software-properties-common     gnupg2     dirmngr     unzip     wget     ghostscript     libgs-dev     imagemagick     sox     sudo     libreoffice     openjdk-11-jre     ffmpeg   && apt-get clean   && rm -rf /var/lib/apt/lists/*     && && wget https://builds.apache.org/view/M-R/view/OpenMeetings/job/openmeetings/lastSuccessfulBuild/artifact/openmeetings-server/target/apache-openmeetings-${OM_VERSION}-SNAPSHOT.tar.gz -O ${work}/om.tar.gz   && tar -xzf ${work}/om.tar.gz --strip-components=1 -C ${OM_HOME}/   && rm -rf ${work}/om.tar.gz   && wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_J_VER}/mysql-connector-java-${MYSQL_J_VER}.jar -P ${OM_HOME}/webapps/openmeetings/WEB-INF/lib   && wget https://repo1.maven.org/maven2/com/ibm/db2/jcc/${DB2_J_VER}/jcc-${DB2_J_VER}.jar -P ${OM_HOME}/webapps/openmeetings/WEB-INF/lib   && sed -i 's|<policy domain="coder" rights="none" pattern="PS" />||g' /etc/ImageMagick-6/policy.xml
 ---> Running in 8cb814769827
/bin/sh: 1: Syntax error: "&&" unexpected
The command '/bin/sh -c cat /etc/issue     && echo "OM server of type ${OM_TYPE} will be built"     && apt-get update && apt-get install -y --no-install-recommends     apt-utils   && apt-get install -y --no-install-recommends     software-properties-common     gnupg2     dirmngr     unzip     wget     ghostscript     libgs-dev     imagemagick     sox     sudo     libreoffice     openjdk-11-jre     ffmpeg   && apt-get clean   && rm -rf /var/lib/apt/lists/*     && && wget https://builds.apache.org/view/M-R/view/OpenMeetings/job/openmeetings/lastSuccessfulBuild/artifact/openmeetings-server/target/apache-openmeetings-${OM_VERSION}-SNAPSHOT.tar.gz -O ${work}/om.tar.gz   && tar -xzf ${work}/om.tar.gz --strip-components=1 -C ${OM_HOME}/   && rm -rf ${work}/om.tar.gz   && wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_J_VER}/mysql-connector-java-${MYSQL_J_VER}.jar -P ${OM_HOME}/webapps/openmeetings/WEB-INF/lib   && wget https://repo1.maven.org/maven2/com/ibm/db2/jcc/${DB2_J_VER}/jcc-${DB2_J_VER}.jar -P ${OM_HOME}/webapps/openmeetings/WEB-INF/lib   && sed -i 's|<policy domain="coder" rights="none" pattern="PS" />||g' /etc/ImageMagick-6/policy.xml' returned a non-zero code: 2
PS C:\Users\djb27\Desktop\openmeetings-docker-master>

**Comment by solomax** [comment]
Should be fixed
