### ISSUE TITLE
ENV variables reset to default after restarting container.

### ISSUE THREAD

**Issue by noddy09** [openmeetings/openmeetings-docker#24]
I created container with -e OM_DB_TYPE=postgresql and provided other enviroment details such as DB credentials and kurento URL also.
To avoid installation from webforms, I just did 
`docker -exec -it om5 /bin/bash
cd /opt/openmeetings
./admin.sh -i -tz Asia/Kolkata -group omgroup -email admin@example.com  -user omadmin --password Pass@123 \
 --db-type postgresql --db-host localhost --db-port 5432 --db-name omdb --db-user omadmin --db-pass Pass@123
exit
`
After exiting from cotainer i restarted container. curl https://localhost:5443 got error response.
I checked logs via `docker logs -f om5`
I saw mysql related error so just again went into container checked environment variable 
via `$OM_DB_TYPE` it returned mysql.

You can check and create conf file just to save env variable values and reuse them even after restart.

**Comment by solomax** [comment]
well
As the result of installation
DB config, as well as new DB are created
I believe docker is being reset on restart

I always thought `om-min` is the version with persistent layer, `om-full` is just mysql demo

Maybe you can provide PR if you know how current version can be improved?

**Comment by noddy09** [comment]
Sure, Also I'm finding way where both kms and om containers can shared /stream directory without restriction of system user access. Soon i will revert back. So lets close this thread for time being.
