### ISSUE TITLE
Problema after install

### ISSUE THREAD

**Issue by profe-jacm** [openmeetings/openmeetings-docker#27]
Hi, I running first pass, but show message 
DEBUG 05-04 16:21:12.831 o.a.o.s.q.s.ReminderJob:93 [Bean#0_Worker-2] - Rss disabled by Admin
DEBUG 05-04 16:31:12.844 o.a.o.s.q.s.ReminderJob:93 [Bean#0_Worker-5] - Rss disabled by Admin
DEBUG 05-04 16:41:12.883 o.a.o.s.q.s.ReminderJob:93 [ean#0_Worker-10] - Rss disabled by Admin
DEBUG 05-04 16:51:12.961 o.a.o.s.q.s.ReminderJob:93 [Bean#0_Worker-8] - Rss disabled by Admin
DEBUG 05-04 17:01:12.846 o.a.o.s.q.s.ReminderJob:93 [ean#0_Worker-10] - Rss disabled by Admin
.......

What to do?

**Comment by solomax** [comment]
This is `DEBUG` information, not error
And I believe it is very much self-descriptive :)
You can enable RSS and it will gone :)
