### ISSUE TITLE
Persistence need to be added to this image

### ISSUE THREAD

**Issue by solomax** [openmeetings/openmeetings-docker#3]
There are 'Data Volumes' and other strategies. http://www.computerweekly.com/feature/Docker-storage-how-to-get-persistent-storage-in-Docker

(as NOTED in #2)

**Comment by Maannniii** [comment]
but still if you want to mounted with file system which folders should be binded to maintain persistance?

**Comment by solomax** [comment]
Following folders need to persist:

1. MySQL DB: `/var/lib/mysql/`
2. User settings and uploaded files: `/opt/red5/webapps/openmeetings/upload`
3. Files related to recordings:: `/opt/red5/webapps/openmeetings/streams`

I guess that's it

**Comment by Maannniii** [comment]
In my case DB is an external container.
Here is my docker file

```
FROM ubuntu:16.04
ENV work /root/work
ENV OM_HOME /opt/red5
WORKDIR ${work}
COPY ffmpeg.sh ./
RUN chmod a+x *.sh
RUN ./ffmpeg.sh
RUN apt-get update && apt-get install sox -y && apt-get install ghostscript -y && apt-get install libfaac-dev -y && apt-get install imagemagick -y && apt-get install -y --no-install-recommends libav-tools && apt-get install openjdk-8-jre -y && apt-get install libreoffice -y --no-install-recommends && apt-get autoclean -y && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*                        
WORKDIR /opt
```
I'm running by mounting `/opt/red5/webapps/openmeetings` but still on restart the presistance is lost. I think it's because of the db and other config getting resetted. Any idea how to preserve those as well?

**Comment by solomax** [comment]
The code above doesn't look like OpenMeetings Docker file
I believe you need to debug your Docker and ensure it works

**Comment by Maannniii** [comment]
@solomax any specific reason for building ffmpeg instead of directly installing from repository?

**Comment by solomax** [comment]
@Maannniii before 4.0.5 ffmped with fdk_aac support was required, 
since 4.0.5 "fresh" ffmpeg is required (to support complex filters)

**Comment by Maannniii** [comment]
@solomax Is there any `unauthenticated API` provided by **Openmeetings** to do health check from docker.

**Comment by solomax** [comment]
@Maannniii you can use `/services/info/version`

**Comment by Maannniii** [comment]
@solomax but that API doesn't guarantee that Openmeetings is healthy.
For example:
If MySQL is down and Open meetings show not initialized but API returns 200.

**Comment by solomax** [comment]
It will return 200, but initialized field will be false
There is no `healthy` flag/method ATM
please create JIRA (https://issues.apache.org/jira/browse/OPENMEETINGS) regarding it

**Comment by Maannniii** [comment]
@solomax any idea about disabling default Tomcat error pages? Also, I've successfully persisted data and made Mysql as a separate container so that the overall size of Openmeetings container is reduced. Trying to implement in alpine will update once done.

**Comment by solomax** [comment]
Is this question somehow relates to the Issue topic?

**Comment by Maannniii** [comment]
@solomax I don't know how to contact you. not sure whether this is an issue or feature. if needed will open a new issue upon ur advice.

**Comment by solomax** [comment]
You can write to the @user mailing list: https://openmeetings.apache.org/mailing-lists.html

**Comment by solomax** [comment]
I believe this issue can be closed
