### ISSUE TITLE
No sound in rooms / no voice communication possible

### ISSUE THREAD

**Issue by Kabbu64** [openmeetings/openmeetings-docker#33]
Hi, 
when I run the container with `docker run -i --name om --netowork host apache/openmeetings:6.2.0` on an - Ubuntu 20.04 Server and Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2 - all seems fine, until I try to check my setup in the dashboard, to see if the configuration of the server is fine.

![grafik](https://user-images.githubusercontent.com/62872814/148734252-f4e4013f-ceee-49d3-9880-2becf3c6b8c8.png)

I try to record my voice but when the timer is over, I am not able to hear my voice. I also made some rooms to try to talk to colleagues, but this does not work either. 

Do I miss a step or miss a configuration? Does the the container maybe miss something? I did not find any entry in the code where a turnserver is installed. Could that be my problem?

**Comment by solomax** [comment]
Which OS/Browser are you using?

**Comment by Kabbu64** [comment]
WIndows 10 / Firefox 95.0.2

**Comment by solomax** [comment]
Did you get `permission dialog`?

**Comment by Kabbu64** [comment]
Where can I find it?

**Comment by solomax** [comment]
Browser usually displays `permission dialog` as soon as web application tries to use camera/microphone:

![Screenshot from 2022-01-10 15-05-58](https://user-images.githubusercontent.com/3870591/148734916-094d6033-a0dc-4b2b-a5ac-690bba6ca779.png)

You should `Allow` using of Camera/Microphone :)

**Comment by solomax** [comment]
BTW can you check if demo works for you as expected: https://om.alteametasoft.com:8443/next/ :))

**Comment by Kabbu64** [comment]
> Browser usually displays `permission dialog` as soon as web application tries to use camera/microphone:
> 
> ![Screenshot from 2022-01-10 15-05-58](https://user-images.githubusercontent.com/3870591/148734916-094d6033-a0dc-4b2b-a5ac-690bba6ca779.png)
> 
> You should `Allow` using of Camera/Microphone :)

Ah yes this shows up and my cam and mic is allowed to use. Also on windows machine.

**Comment by Kabbu64** [comment]
> BTW can you check if demo works for you as expected: https://om.alteametasoft.com:8443/next/ :))

You want me to register on this OM and check my setup there?

We have another instance of OM on another standalone Server with an older version of OM, which was installed manually, where my mic and my cam work carefree. The issue only occurs in the container. 
I tried to check the setup again and I do not know why, but it worked.... Sometimes I can hear myself, sometimes I cannot. I checked the firewall as well. Nothing blocking the traffic from my internal Network into the public machine. But since it isn't working all the time I'm checking the setup, there must be still some issues I do not fully understand yet. Either in the container itself, or in my network....

**Comment by solomax** [comment]
You can check your audio/video at any OM server using URL like this `https://om.alteametasoft.com:8443/next/hash?app=settings` :)

the only other option I can propose: is to additionally check browser JS console :)

I need more details to be able to help :)

**Comment by solomax** [comment]
feel free to re-open with additional details :))
