### ISSUE TITLE
During screen recording, this type of file *.webm was not found in the opt / omdata directory

### ISSUE THREAD

**Issue by remzhangzxx** [openmeetings/openmeetings-docker#35]
I execute the following command line:
docker run -p 5443:5443 \
-e OM_KURENTO_WS_URL="ws://192.168.0.171:30008/kurento" \
-e OM_DB_HOST=192.168.0.171 \
-e OM_DB_USER=openmeetings \
-e OM_DB_PASS=wanlingwk123 \
-e OM_DB_PORT=30031 \
-v /opt/omdata:/opt/omdata \
-it apache/openmeetings:min-6.2.0

In the process of uploading files, it is found that the / opt / omdata directory does not have permission。
![cannotrecord](https://user-images.githubusercontent.com/18411092/154791311-4d2695d8-aef0-4370-abc4-1ce74d42f337.png)

Recording file is not found!
----------------------can not record and not found *.webm files------------------------------------------
process: generate MP4
command: /usr/bin/ffmpeg -y -itsoffset 00:00:01.183 -i /opt/omdata/streams/9/rec_4_6eac95a5-a844-4460-a5d8-13511c31443a.webm -i /opt/omdata/streams/9/rec_4_6eac95a5-a844-4460-a5d8-13511c31443a_FINAL_WAVE.wav -c:v h264 -crf 24 -vsync 0 -pix_fmt yuv420p -preset medium -profile:v baseline -level 3.0 -movflags faststart -c:a aac -ar 22050 -b:a 32k -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /opt/omdata/streams/hibernate/37b6da58-fa59-4625-b526-f55b390a207a.mp4
exception: null
error: ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
![cannotrecord](https://user-images.githubusercontent.com/18411092/154790871-7d4fe142-a048-4da7-ae4a-78d413c2351a.png)

  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
/opt/omdata/streams/9/rec_4_6eac95a5-a844-4460-a5d8-13511c31443a.webm: No such file or directory
exitValue: 1
optional: false
out: 
----------------------------------------------------------------------------------
thanks!

**Comment by remzhangzxx** [comment]
beacuse /opt/omdata not shared.

**Comment by solomax** [comment]
yes :)
it should be shared with KMS docker as well :)))
