### ISSUE TITLE
How to store data in a container to an external on-premises MySQL database

### ISSUE THREAD

**Issue by searchuse** [openmeetings/openmeetings-docker#38]
Hello, I want to store the saved data generated in the container to mysql outside the container to prevent data loss in the event of a container failure. After restarting the container, the data stored in the external MySQL database will be read, and the data configuration can be the same as the previous container, such as the added users

**Comment by solomax** [comment]
Hello @searchuse,

sorry for the late reply

please use https://github.com/openmeetings/openmeetings-docker?tab=readme-ov-file#to-run-mini-om and provide external DB URL/credentials :)
