### ISSUE TITLE
NginX

### ISSUE THREAD

**Issue by nareshk01** [openmeetings/openmeetings-docker#4]
Can you please provide NginX Reverse proxy configuration for OpenMeetings ?
I'm able to open homepage (ex- openmeetings.zox.work)
But when i try to sign in , it does nothing 
Error i get : GET http://openmeetings.zox.work/openmeetings/wicket/bookmarkable/org.apache.openmeetings.web.pages.auth.SignInPage...long text...     400 Error
When i click on network testing , it throws HTTP Status 400 – Bad Request

My current NgiNx file :+1: 
server {
listen 80;
server_name openmeetings.zox.work;
access_log off;
client_max_body_size 1024M;
error_log /var/log/nginx/error.log;
location / {
proxy_pass http://172.16.0.101:5080;

}
}

**Comment by solomax** [comment]
Unfortunately I can't help here
