### ISSUE TITLE
Cent OS 7 doesnt work

### ISSUE THREAD

**Issue by daddydrac** [openmeetings/openmeetings-docker#9]
Pulled down the container, followed instructions, and all I get is:
DEBUG 10-27 14:58:29.745 o.a.o.s.q.s.ReminderJob:92 [Bean#0_Worker-7] - Rss disabled by Admin

**Comment by daddydrac** [comment]
I think it has something to do with <HASHED_PWD>  in:

docker login -u openmeetings -p <HASHED_PWD> openmeetings-docker-images.bintray.io

Is there a specific one or can I use my own?

**Comment by solomax** [comment]
Hello @joehoeller,

Actually as a result you should get running OM
with some continuous logs in console
So I can see no issue

According to your second post regarding `docker login`: these steps are for the publishing of docker image to bintray
I'm afraid I can't give you official account details :)
